/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: score_update.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "score_update.pb-c.h"
void   score_update__init
                     (ScoreUpdate         *message)
{
  static const ScoreUpdate init_value = SCORE_UPDATE__INIT;
  *message = init_value;
}
size_t score_update__get_packed_size
                     (const ScoreUpdate *message)
{
  assert(message->base.descriptor == &score_update__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t score_update__pack
                     (const ScoreUpdate *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &score_update__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t score_update__pack_to_buffer
                     (const ScoreUpdate *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &score_update__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ScoreUpdate *
       score_update__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ScoreUpdate *)
     protobuf_c_message_unpack (&score_update__descriptor,
                                allocator, len, data);
}
void   score_update__free_unpacked
                     (ScoreUpdate *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &score_update__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   score_updates__init
                     (ScoreUpdates         *message)
{
  static const ScoreUpdates init_value = SCORE_UPDATES__INIT;
  *message = init_value;
}
size_t score_updates__get_packed_size
                     (const ScoreUpdates *message)
{
  assert(message->base.descriptor == &score_updates__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t score_updates__pack
                     (const ScoreUpdates *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &score_updates__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t score_updates__pack_to_buffer
                     (const ScoreUpdates *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &score_updates__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ScoreUpdates *
       score_updates__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ScoreUpdates *)
     protobuf_c_message_unpack (&score_updates__descriptor,
                                allocator, len, data);
}
void   score_updates__free_unpacked
                     (ScoreUpdates *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &score_updates__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor score_update__field_descriptors[2] =
{
  {
    "ch",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ScoreUpdate, ch),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "score",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ScoreUpdate, score),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned score_update__field_indices_by_name[] = {
  0,   /* field[0] = ch */
  1,   /* field[1] = score */
};
static const ProtobufCIntRange score_update__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor score_update__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ScoreUpdate",
  "ScoreUpdate",
  "ScoreUpdate",
  "",
  sizeof(ScoreUpdate),
  2,
  score_update__field_descriptors,
  score_update__field_indices_by_name,
  1,  score_update__number_ranges,
  (ProtobufCMessageInit) score_update__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor score_updates__field_descriptors[1] =
{
  {
    "scores",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ScoreUpdates, n_scores),
    offsetof(ScoreUpdates, scores),
    &score_update__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned score_updates__field_indices_by_name[] = {
  0,   /* field[0] = scores */
};
static const ProtobufCIntRange score_updates__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor score_updates__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ScoreUpdates",
  "ScoreUpdates",
  "ScoreUpdates",
  "",
  sizeof(ScoreUpdates),
  1,
  score_updates__field_descriptors,
  score_updates__field_indices_by_name,
  1,  score_updates__number_ranges,
  (ProtobufCMessageInit) score_updates__init,
  NULL,NULL,NULL    /* reserved[123] */
};
