# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: score_update.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12score_update.proto\"(\n\x0bScoreUpdate\x12\n\n\x02\x63h\x18\x01 \x02(\x05\x12\r\n\x05score\x18\x02 \x02(\x05\",\n\x0cScoreUpdates\x12\x1c\n\x06scores\x18\x01 \x03(\x0b\x32\x0c.ScoreUpdate')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'score_update_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SCOREUPDATE._serialized_start=22
  _SCOREUPDATE._serialized_end=62
  _SCOREUPDATES._serialized_start=64
  _SCOREUPDATES._serialized_end=108
# @@protoc_insertion_point(module_scope)
